const { ROLES } = require('./roles');

/**
 * Permission Configuration
 * Defines what each role can do
 */
const PERMISSIONS = {
  // User Management
  USER_CREATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  USER_READ: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.AUDITOR],
  USER_UPDATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  USER_DELETE: [ROLES.SUPER_ADMIN],

  // Member Management
  MEMBER_CREATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.VOLUNTEER_MANAGER],
  MEMBER_READ: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT, ROLES.EVENT_MANAGER, ROLES.VOLUNTEER_MANAGER, ROLES.AUDITOR],
  MEMBER_UPDATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.VOLUNTEER_MANAGER],
  MEMBER_DELETE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],

  // Donation Management
  DONATION_CREATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT],
  DONATION_READ: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT, ROLES.AUDITOR],
  DONATION_UPDATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT],
  DONATION_DELETE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],

  // Expense Management
  EXPENSE_CREATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT, ROLES.EVENT_MANAGER],
  EXPENSE_READ: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT, ROLES.EVENT_MANAGER, ROLES.AUDITOR],
  EXPENSE_UPDATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT],
  EXPENSE_APPROVE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT],
  EXPENSE_DELETE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],

  // Event Management
  EVENT_CREATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.EVENT_MANAGER],
  EVENT_READ: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT, ROLES.EVENT_MANAGER, ROLES.VOLUNTEER_MANAGER, ROLES.AUDITOR],
  EVENT_UPDATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.EVENT_MANAGER],
  EVENT_DELETE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],

  // Volunteer Management
  VOLUNTEER_CREATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.VOLUNTEER_MANAGER],
  VOLUNTEER_READ: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.EVENT_MANAGER, ROLES.VOLUNTEER_MANAGER, ROLES.AUDITOR],
  VOLUNTEER_UPDATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.VOLUNTEER_MANAGER],
  VOLUNTEER_DELETE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],

  // Wallet Management
  WALLET_READ: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT, ROLES.AUDITOR],

  // Document Management
  DOCUMENT_CREATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  DOCUMENT_READ: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT, ROLES.EVENT_MANAGER, ROLES.AUDITOR],
  DOCUMENT_UPDATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  DOCUMENT_DELETE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],

  // Audit Logs
  AUDIT_READ: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.AUDITOR],

  // Content Management (CMS)
  CONTENT_CREATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.CONTENT_MANAGER],
  CONTENT_READ: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.CONTENT_MANAGER, ROLES.EVENT_MANAGER, ROLES.AUDITOR],
  CONTENT_UPDATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.CONTENT_MANAGER],
  CONTENT_PUBLISH: [ROLES.SUPER_ADMIN, ROLES.ADMIN], // Only admins can publish
  CONTENT_DELETE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],

  // Gallery Management
  GALLERY_CREATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.CONTENT_MANAGER, ROLES.EVENT_MANAGER],
  GALLERY_READ: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.CONTENT_MANAGER, ROLES.EVENT_MANAGER, ROLES.AUDITOR],
  GALLERY_UPDATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.CONTENT_MANAGER],
  GALLERY_DELETE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],

  // Testimonial Management
  TESTIMONIAL_CREATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.CONTENT_MANAGER],
  TESTIMONIAL_READ: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.CONTENT_MANAGER, ROLES.AUDITOR],
  TESTIMONIAL_APPROVE: [ROLES.SUPER_ADMIN, ROLES.ADMIN], // Approval required
  TESTIMONIAL_UPDATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.CONTENT_MANAGER],
  TESTIMONIAL_DELETE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],

  // Site Settings
  SETTINGS_READ: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.CONTENT_MANAGER, ROLES.AUDITOR],
  SETTINGS_UPDATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],

  // Contact Submissions
  CONTACT_READ: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.CONTENT_MANAGER],
  CONTACT_REPLY: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.CONTENT_MANAGER],
  CONTACT_DELETE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],

  // Volunteer Registrations (from mainsite)
  VOLUNTEER_REG_READ: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.VOLUNTEER_MANAGER],
  VOLUNTEER_REG_UPDATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.VOLUNTEER_MANAGER],
  VOLUNTEER_REG_DELETE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],

  // Dynamic Form Management
  FORM_CREATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.EVENT_MANAGER],
  FORM_READ: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.EVENT_MANAGER, ROLES.VOLUNTEER_MANAGER, ROLES.AUDITOR],
  FORM_UPDATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.EVENT_MANAGER],
  FORM_DELETE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  FORM_SUBMISSION_READ: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.EVENT_MANAGER, ROLES.VOLUNTEER_MANAGER, ROLES.AUDITOR],
  FORM_SUBMISSION_UPDATE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.EVENT_MANAGER],
  FORM_SUBMISSION_DELETE: [ROLES.SUPER_ADMIN, ROLES.ADMIN]
};

/**
 * Check if a role has a specific permission
 */
const hasPermission = (role, permission) => {
  const allowedRoles = PERMISSIONS[permission];
  if (!allowedRoles) return false;
  return allowedRoles.includes(role);
};

/**
 * Check if a role is read-only (AUDITOR)
 */
const isReadOnly = (role) => {
  return role === ROLES.AUDITOR;
};

module.exports = {
  PERMISSIONS,
  hasPermission,
  isReadOnly
};


